### ISSUE TITLE
Recommended Java version

### ISSUE THREAD

**Issue by wguttmn** [UniconLabs/simple-cas4-overlay-template#12]
According to https://github.com/UniconLabs/simple-cas4-overlay-template, Java 1.8 is recommended, but the Maven POM still refers to Java 1.7 as per:
```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.3</version>
                <configuration>
                    <source>1.7</source>
                    <target>1.7</target>
                </configuration>
            </plugin>
```

So what's the final verdict ?

**Comment by mmoayyed** [comment]
I think 1.7 is the minimum supported version. You can use both.

**Comment by mmoayyed** [comment]
This plugin is not used to deploy CAS itself, but it simply is able to compile Java classes that are put into the overlay. For CAS itself, you need 1.7+ plus.

**Comment by mmoayyed** [comment]
Fixed readme
