### ISSUE TITLE
Branch Tag

### ISSUE THREAD

**Issue by dasibre** [UniconLabs/simple-cas4-overlay-template#16]
Have the branch tags been removed? My automated build depended on 4.1 tags, seems that is no longer used? Please confirm.

**Comment by mmoayyed** [comment]
Commit log does not show any removals. Master is on 4.1

**Comment by mmoayyed** [comment]
You may also want to keep an eye on https://github.com/Jasig/cas-overlay-template which is a clone of the same project here, but maintained by the CAS folks.

**Comment by dasibre** [comment]
Thanks @mmoayyed
