### ISSUE TITLE
Build Problem

### ISSUE THREAD

**Issue by farzadkh** [UniconLabs/simple-cas4-overlay-template#8]
I've just built the project and got these warnings and error which failed the build operation:

.
.
.
8K downloaded  (maven-2.0.pom)
Downloading: http://oss.sonatype.org/content/repositories/releases//org/apache/m
aven/maven-profile/2.0/maven-profile-2.0.pom
178b downloaded  (maven-profile-2.0.pom)
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = '81ffbd1712
afe8cdf138b570c0fc9934742c33c1'; remote = '<html>
<head><title>301' - RETRYING
Downloading: http://oss.sonatype.org/content/repositories/releases//org/apache/m
aven/maven-profile/2.0/maven-profile-2.0.pom
178b downloaded  (maven-profile-2.0.pom)
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = '81ffbd1712
afe8cdf138b570c0fc9934742c33c1'; remote = '<html>
<head><title>301' - IGNORING
[WARNING] POM for 'org.apache.maven:maven-profile:pom:2.0:runtime' is invalid.

Its dependencies (if any) will NOT be available to the current build.
Downloading: http://oss.sonatype.org/content/repositories/releases//org/apache/m
aven/maven-model/2.0/maven-model-2.0.pom
178b downloaded  (maven-model-2.0.pom)
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = '81ffbd1712
afe8cdf138b570c0fc9934742c33c1'; remote = '<html>
<head><title>301' - RETRYING
Downloading: http://oss.sonatype.org/content/repositories/releases//org/apache/m
aven/maven-model/2.0/maven-model-2.0.pom
178b downloaded  (maven-model-2.0.pom)
[WARNING] *** CHECKSUM FAILED - Checksum failed on download: local = '81ffbd1712
afe8cdf138b570c0fc9934742c33c1'; remote = '<html>
<head><title>301' - IGNORING
[WARNING] POM for 'org.apache.maven:maven-model:pom:2.0:runtime' is invalid.
.
.
.

It seems that this is because CodeHaus is out of operation now and the redirects aren't working.

**Comment by mmoayyed** [comment]
Looks like you are using Maven2 to build, right?

**Comment by dima767** [comment]
Maven 2 not supported. Run `mvn -version` and if it's 2.x, upgrade to the latest Maven version. Also, you might want to clear your `.m2` cache, just to start clean.

**Comment by farzadkh** [comment]
Solved. Thank you very much.
