### ISSUE TITLE
Make sure 4.1 branch runs smoothly

### ISSUE THREAD

**Issue by mmoayyed** [UniconLabs/simple-cas4-overlay-template#9]
A few properties attempt to be missing from the 4.1 branch. Apply and correct.

**Comment by mmoayyed** [comment]
@dbhankins please also make sure log4j config is compatible with 4.1. Presently, it's not. It needs to support log4j 2.

**Comment by dima767** [comment]
So @mmoayyed , basically that means - just bring the following config down to `etc`: https://github.com/Jasig/cas/blob/master/cas-server-webapp/src/main/resources/log4j2.xml , I would think.

**Comment by mmoayyed** [comment]
yup, and do account for the Unicon specific changes, if there are any.

**Comment by dbhankins** [comment]
Does it need to support both log4j and log4j 2, or just the latter? And there will need to be a property added to cas.properties to point to log4j2.xml, yes?

There are no com.github references in log4j2.xml, nor anything else data-wise that looked like it needs changing to be Unicon-compliant.

However, the file header has an Apereo license statement. I would expect we want to replace that with the Jasig one, yes?

**Comment by dima767** [comment]
No - there is no my Jasig. It's Apereo now. So officially, it's `Apereo CAS`. It's kind of unfortunate that Github organization is still Jasig

**Comment by dbhankins** [comment]
So should I be going through all the source files and replacing the Jasig license header comments with Apereo ones? Or just cas.properties? Or leave well enough alone and maybe open an issue for it?

**Comment by dima767** [comment]
I'd say just leave it alone for now
